################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
utils \
src/tools/visualizer/model \
src/test \
src/test/perf \
src/test/nsctcp \
src/test/ns3wifi \
src/test/ns3tcp \
src/simulator \
src/routing/static-routing/model \
src/routing/static-routing/helper \
src/routing/olsr/test \
src/routing/olsr/model \
src/routing/olsr/helper \
src/routing/olsr/examples \
src/routing/nix-vector-routing \
src/routing/list-routing/model \
src/routing/list-routing/helper \
src/routing/global-routing/model \
src/routing/global-routing/helper \
src/routing/dsdv/test \
src/routing/dsdv/model \
src/routing/dsdv/helper \
src/routing/dsdv/examples \
src/routing/aodv/test \
src/routing/aodv \
src/node \
src/mpi \
src/mobility \
src/internet-stack \
src/helper \
src/devices/wimax \
src/devices/wifi \
src/devices/virtual-net-device/model \
src/devices/virtual-net-device/examples \
src/devices/uan/test \
src/devices/uan/model \
src/devices/uan/helper \
src/devices/uan/examples \
src/devices/tap-bridge \
src/devices/spectrum \
src/devices/point-to-point \
src/devices/mesh \
src/devices/mesh/flame/test \
src/devices/mesh/flame \
src/devices/mesh/dot11s/test \
src/devices/mesh/dot11s \
src/devices/lte/test \
src/devices/lte/model \
src/devices/lte/helper \
src/devices/lte/examples \
src/devices/emu \
src/devices/csma \
src/devices/bridge/model \
src/devices/bridge/helper \
src/devices/bridge/examples \
src/core \
src/contrib \
src/contrib/topology-read \
src/contrib/stats \
src/contrib/flow-monitor/model \
src/contrib/flow-monitor/helper \
src/contrib/energy/test \
src/contrib/energy/model \
src/contrib/energy/helper \
src/contrib/energy/examples \
src/common \
src/applications/v4ping \
src/applications/udp-echo \
src/applications/udp-client-server \
src/applications/radvd \
src/applications/ping6 \
src/applications/packet-sink \
src/applications/onoff \
src/applications/bulk-send \
scratch \
scratch/multiple-sources \
samples \
examples/wireless \
examples/wimax \
examples/udp-client-server \
examples/udp \
examples/tutorial \
examples/topology-read \
examples/tcp \
examples/tap \
examples/stats \
examples/spectrum \
examples/socket \
examples/routing \
examples/realtime \
examples/naming \
examples/mpi \
examples/mobility \
examples/mesh \
examples/matrix-topology \
examples/ipv6 \
examples/error-model \
examples/energy \
examples/emulation \
examples/csma \
examples/animation \
bindings/python \

