## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
     obj = bld.create_ns3_program('secure-batman-manet', ['wifi', 'internet-stack', 'batman'])
     obj.source = 'secure-batman-manet.cc'

